"""Cypher export for extracted entities and relationships."""

from __future__ import annotations

import json
from typing import Any

from crypto_kg.models import Entity, ExtractionResult, Relation


def export_cypher(result: ExtractionResult, include_system_relation: bool = True) -> str:
    lines: list[str] = [
        "// Generated by crypto_kg. Review before applying to production Neo4j.",
    ]
    for entity in result.entities:
        lines.extend(entity_to_cypher(entity))
        if include_system_relation and entity.properties.get("system_id"):
            lines.extend(system_relation_to_cypher(entity))
        if entity.properties.get("product_type_code") and "CryptoProduct" in entity.labels:
            lines.extend(product_type_relation_to_cypher(entity))
        if entity.properties.get("data_category_code") and "ImportantData" in entity.labels:
            lines.extend(data_category_relation_to_cypher(entity))
    for relation in dedupe_relations(result.relations):
        lines.extend(relation_to_cypher(relation))
    return "\n".join(lines) + "\n"


def entity_to_cypher(entity: Entity) -> list[str]:
    labels = ":".join(entity.labels)
    props = cypher_map(entity.all_properties())
    return [
        f"MERGE (n:{labels} {{id: {cypher_value(entity.id)}}})",
        f"SET n += {props};",
        "",
    ]


def system_relation_to_cypher(entity: Entity) -> list[str]:
    system_id = entity.properties["system_id"]
    lines: list[str] = []
    for relation_type in relation_types_for_entity(entity):
        lines.extend(
            [
                f"MATCH (s:System {{id: {cypher_value(system_id)}}})",
                f"MATCH (n:Entity {{id: {cypher_value(entity.id)}}})",
                f"MERGE (s)-[r:{relation_type}]->(n)",
                "SET r.confidence = coalesce(r.confidence, n.confidence), r.source_section = n.source_section;",
                "",
            ]
        )
    return lines


def product_type_relation_to_cypher(entity: Entity) -> list[str]:
    code = entity.properties["product_type_code"]
    return [
        f"MATCH (n:Entity {{id: {cypher_value(entity.id)}}})",
        f"MATCH (t:ProductType {{code: {cypher_value(code)}}})",
        "MERGE (n)-[:HAS_PRODUCT_TYPE]->(t);",
        "",
    ]


def data_category_relation_to_cypher(entity: Entity) -> list[str]:
    code = entity.properties["data_category_code"]
    return [
        f"MATCH (n:Entity {{id: {cypher_value(entity.id)}}})",
        f"MATCH (t:DataCategory {{code: {cypher_value(code)}}})",
        "MERGE (n)-[:HAS_DATA_CATEGORY]->(t);",
        "",
    ]


def relation_to_cypher(relation: Relation) -> list[str]:
    props = cypher_map(relation.properties)
    if relation.type == "USES_ALGORITHM":
        end_match = f"MATCH (b:CryptoAlgorithm {{name: {cypher_value(relation.end_id)}}})"
    elif relation.type in {"HAS_USAGE", "SATISFIES"}:
        label = "CryptoUsage" if relation.type == "HAS_USAGE" else "SecurityRequirement"
        end_match = f"MATCH (b:{label} {{name: {cypher_value(relation.end_id)}}})"
    else:
        end_match = f"MATCH (b {{id: {cypher_value(relation.end_id)}}})"
    return [
        f"MATCH (a:Entity {{id: {cypher_value(relation.start_id)}}})",
        end_match,
        f"MERGE (a)-[r:{relation.type}]->(b)",
        f"SET r += {props};",
        "",
    ]


def relation_types_for_entity(entity: Entity) -> list[str]:
    mapping = {
        "PhysicalEnvironment": "HAS_PHYSICAL_ENVIRONMENT",
        "PhysicalSecurityFacility": "HAS_SECURITY_FACILITY",
        "CryptoProduct": "HAS_CRYPTO_PRODUCT",
        "Server": "HAS_SERVER",
        "NetworkDevice": "HAS_NETWORK_DEVICE",
        "DatabaseSystem": "USES_DATABASE",
        "Middleware": "HAS_MIDDLEWARE",
        "BusinessApplication": "HAS_APPLICATION",
        "ImportantData": "HAS_IMPORTANT_DATA",
        "ManagementDocument": "HAS_DOCUMENT",
        "Person": "HAS_PERSON",
        "UserRole": "HAS_USER_ROLE",
        "SecurityArea": "HAS_SECURITY_AREA",
        "NetworkLink": "HAS_NETWORK_LINK",
        "CryptoService": "USES_CRYPTO_SERVICE",
        "CryptoApplication": "HAS_CRYPTO_APPLICATION",
        "ComplianceItem": "HAS_COMPLIANCE_ITEM",
    }
    relations: list[str] = []
    for label in entity.labels:
        if label in mapping:
            relations.append(mapping[label])
    return list(dict.fromkeys(relations)) or ["HAS_ENTITY"]


def dedupe_relations(relations: list[Relation]) -> list[Relation]:
    seen: set[tuple[str, str, str]] = set()
    result: list[Relation] = []
    for relation in relations:
        key = (relation.start_id, relation.type, relation.end_id)
        if key in seen:
            continue
        seen.add(key)
        result.append(relation)
    return result


def cypher_map(values: dict[str, Any]) -> str:
    items = []
    for key, value in values.items():
        if value in (None, "", []):
            continue
        items.append(f"{key}: {cypher_value(value)}")
    return "{" + ", ".join(items) + "}"


def cypher_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(cypher_value(item) for item in value) + "]"
    if isinstance(value, dict):
        return cypher_map(value)
    return json.dumps(str(value), ensure_ascii=False)
